// This file is generated

S_author_0 = [
"US Commissioner of Pensions",
"John Lovell",
"Aline Tremblay",
"Conseil G\u00e9n\u00e9ral de la Charente-Maritime",
"Direction des archives et des biens culturels de l'Orne",
"",
"Francis Maurus Kearns & Dianne Wood",
"Soci\u00e9t\u00e9 G\u00e9n\u00e9alogique Canadienne Fran\u00e7aise",
"Groupe BMS2000",
"Fabrique de St-Malo",
"Canadian Headstones",
"",
"Catholic Church. Assumption of the Blessed Virgin Mary (Redford, New York)",
"Catholic Church. St. Peter (Plattsburgh, New York)",
"BAnQ",
"Marcel Fournier",
"Find A Grave, Inc",
"Cour Sup\u00e9rieure, district judiciaire de Qu\u00e9bec",
"Marcel Walter Landry",
"",
"Gilbert Benoit",
"Biblioth\u00e8que et archives Nationales Qu\u00e9bec",
"Pierre-Georges Roy; Antoine Roy",
"Institut g\u00e9n\u00e9alogique Drouin",
"",
"Institut g\u00e9n\u00e9alogique Drouin",
"Brasserie Labatt",
"Chevassu, Patrick",
"Benoit Pontbriand",
"Holbrook Research Institute (Jay and Delene Holbrook).",
"New York State Archives, Albany, New York",
"vari\u00e9s",
"images FamilySearch",
"D\u00e9partement de d\u00e9mographie - Universit\u00e9 de Montr\u00e9al",
"images, FamilySearch",
"FamilySearch, index and images",
"",
"",
"",
"",
"",
"",
"",
"Repos St-Fran\u00e7ois d'Assise",
"BanQ",
"Ancestry.com. Original data: Institut g\u00e9n\u00e9alogique Drouin",
"Institut g\u00e9n\u00e9alogique Drouin",
"Ancestry.com. Original data: Institut g\u00e9n\u00e9alogique Drouin",
"J.T. Recherches inc",
"Warren Dow",
"George C. Edgar",
"Patricia Leight leighthouse@rochester.rr.com"
]
Dwr.ScriptLoaded('dwr_db_S_author_0.js');
