// This file is generated

S_text_0 = [
"<p>\n<b>\nAuteur: \n</b>\nUS Commissioner of Pensions\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nJohn Lovell\n</p><p>\n<b>\nAbr\u00e9viation: \n</b>\nLovell\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nAline Tremblay\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nConseil G\u00e9n\u00e9ral de la Charente-Maritime\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nDirection des archives et des biens culturels de l'Orne\n</p>",
"",
"<p>\n<b>\nAuteur: \n</b>\nFrancis Maurus Kearns & Dianne Wood\n</p><p>\n<b>\nInformations de publication: \n</b>\nNorthern New York American-Canadian Genealogical Society\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nSoci\u00e9t\u00e9 G\u00e9n\u00e9alogique Canadienne Fran\u00e7aise\n</p><p>\n<b>\nAbr\u00e9viation: \n</b>\nD\u00e9c\u00e8s -SGCF\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nGroupe BMS2000\n</p><p>\n<b>\nAbr\u00e9viation: \n</b>\nbms2k\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nFabrique de St-Malo\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nCanadian Headstones\n</p>",
"",
"<p>\n<b>\nAuteur: \n</b>\nCatholic Church. Assumption of the Blessed Virgin Mary (Redford, New York)\n</p><p>\n<b>\nInformations de publication: \n</b>\nSalt Lake City, Utah: Filmed by the Genealogical Society of Utah, 1986.\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nCatholic Church. St. Peter (Plattsburgh, New York)\n</p><p>\n<b>\nInformations de publication: \n</b>\nSalt Lake City, Utah : Filmed by the Genealogical Society of Utah, 1986\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nBAnQ\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nMarcel Fournier\n</p><p>\n<b>\nInformations de publication: \n</b>\nCopyright 1999-2015 F\u00e9d\u00e9ration qu\u00e9b\u00e9coise des soci\u00e9t\u00e9s de g\u00e9n\u00e9alogie\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nFind A Grave, Inc\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nCour Sup\u00e9rieure, district judiciaire de Qu\u00e9bec\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nMarcel Walter Landry\n</p>",
"<p>\n<b>\nInformations de publication: \n</b>\nhttp://www.famille-arbour.com/2012/12/19/genealogie-famille-charland-denis-1656/#more-8026\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nGilbert Benoit\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nBiblioth\u00e8que et archives Nationales Qu\u00e9bec\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nPierre-Georges Roy; Antoine Roy\n</p><p>\n<b>\nInformations de publication: \n</b>\nArchives nationales du Qu\u00e9bec\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nInstitut g\u00e9n\u00e9alogique Drouin\n</p>",
"",
"<p>\n<b>\nAuteur: \n</b>\nInstitut g\u00e9n\u00e9alogique Drouin\n</p><p>\n<b>\nAbr\u00e9viation: \n</b>\nLAFRANCE\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nBrasserie Labatt\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nChevassu, Patrick\n</p><p>\n<b>\nInformations de publication: \n</b>\nLes \u00e9ditions Tremblay, 1981\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nBenoit Pontbriand\n</p><p>\n<b>\nInformations de publication: \n</b>\n1984\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nHolbrook Research Institute (Jay and Delene Holbrook).\n</p><p>\n<b>\nInformations de publication: \n</b>\n[database on-line]. Provo, UT, USA: Ancestry.com Operations, Inc., 2011\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nNew York State Archives, Albany, New York\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nvari\u00e9s\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nimages FamilySearch\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nD\u00e9partement de d\u00e9mographie - Universit\u00e9 de Montr\u00e9al\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nimages, FamilySearch\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nFamilySearch, index and images\n</p>",
"",
"",
"",
"",
"",
"",
"",
"<p>\n<b>\nAuteur: \n</b>\nRepos St-Fran\u00e7ois d'Assise\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nBanQ\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nAncestry.com. Original data: Institut g\u00e9n\u00e9alogique Drouin\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nInstitut g\u00e9n\u00e9alogique Drouin\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nAncestry.com. Original data: Institut g\u00e9n\u00e9alogique Drouin\n</p><p>\n<b>\nAbr\u00e9viation: \n</b>\nCollection Drouin\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nJ.T. Recherches inc\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nWarren Dow\n</p><p>\n<b>\nInformations de publication: \n</b>\n(Plattsburgh, N.Y.) 1861-1902\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nGeorge C. Edgar\n</p><p>\n<b>\nInformations de publication: \n</b>\n(Tupper Lake, N.Y.) 1895-1924\n</p>",
"<p>\n<b>\nAuteur: \n</b>\nPatricia Leight leighthouse@rochester.rr.com\n</p>"
]
Dwr.ScriptLoaded('dwr_db_S_text_0.js');
