// This file is generated

S_note_0 = [
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nNote sur la source\n</i>\n<div class=\"grampsstylednote\">\n<p>\nLe r\u00e9pertoire informatis\u00e9 des actes trouv\u00e9s dans le cadre du projet franco-qu\u00e9b\u00e9cois de recherche sur les origines familiales des \u00e9migrants fran\u00e7ais et \u00e9trangers \u00e9tablis au Qu\u00e9bec des origines \u00e0 1865.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nNote sur la source\n</i>\n<div class=\"grampsstylednote\">\n<p>\nLe LAFRANCE - Mise \u00e0 jour Octobre 2016\n</p>\n<p>\nL'Am\u00e9rique fran\u00e7aise : registres anciens et nouveaux et ses collections effectives\n</p>\n<p>\nCouvre toute la p\u00e9riode 1621-1849 du Qu\u00e9bec catholique et les actes de mariage catholiques du Qu\u00e9bec 1825-1915. Comprend plusieurs actes BS pour la p\u00e9riode 1850-1861 et certains jusqu'en 2008.<br />\n3 421 559 actes NBMDS.<br />\nLien \u00e0 l'image de l'acte du Fonds Drouin.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nNote sur la source\n</i>\n<div class=\"grampsstylednote\">\n<p>\nThis collection contains muster roll abstracts of New York State Infantry units that served in the Civil War. The records are from microfilm found at the New York State Archives and contain 550,000 records spanning 395 volumes. The beginning of the regiment record includes information on the regiment and may contain a detailed history of the unit. The individual records may contain name, date of enlistment, age, place of enlistment, grade, company, regiment, reason for leaving, promotions, participation in engagements, wounds, and physical appearance.\n</p>\n</div>\n</div>",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"<div>\n<i class=\"NoteType\">\nNote sur la source\n</i>\n<div class=\"grampsstylednote\">\n<p>\nAncestry.com. Registres de l\u2019\u00c9glise catholique de l\u2019Ontario (Collection Drouin), 1747 \u00e0 1967 [database on-line]. Provo, UT, USA: Ancestry.com Operations Inc, 2007.<br />\nInformation originale : Gabriel Drouin, comp. Drouin Collection. Montr\u00e9al, Qu\u00e9bec, Canada: Institut G\u00e9n\u00e9alogique Drouin.\n</p>\n</div>\n</div>",
"",
"<div>\n<i class=\"NoteType\">\nNote sur la source\n</i>\n<div class=\"grampsstylednote\">\n<p>\nAncestry.com. Registres paroissiaux et Actes d\u2019\u00e9tat civil du Qu\u00e9bec (Collection Drouin), 1621 \u00e0 1967 [base de donn\u00e9es en ligne]. Provo, UT, USA: Ancestry.com Operations Inc, 2008.<br />\nDonn\u00e9es originales : Gabriel Drouin, comp. Drouin Collection. Montr\u00e9al, Qu\u00e9bec, Canada: Institut G\u00e9n\u00e9alogique Drouin.\n</p>\n</div>\n</div>",
"",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_S_note_0.js');
